### PR TITLE
Added necessary changes for the new retry logic for HttpYouViewClient…

### PR DESCRIPTION
**Pull request by MartinsIrbe**
Added necessary changes for the new retry logic for HttpYouViewClient to retry when the request response retrun http code >= 500. Also removed current retry logic.

### CODE REVIEW

**Comment by JamieAP** [comment]
LGTM

**Comment by tfm** [comment]
How does this commit relate to the commits on the other task branches?

**Comment by MartinsIrbe** [comment]
@tfm this commit contains both changes for removing existing retry logic and adding the new retry logic. I just wanted to make sure that I haven't missed anything. :)

**Comment by tfm** [comment]
Then cherry-pick the other commits, don't make a new one :)

**Pull request merged**
